### ISSUE TITLE
OpenCV 3.0 build fails on Ubuntu 12.04

### ISSUE THREAD

**Issue by ulrichstern** [Itseez/opencv#5131]
I used the official 3.0 release (http://opencv.org/downloads.html) and ran into this during a build on Ubuntu 12.04:

    ...
    [ 16%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_ffmpeg.cpp.o
    In file included from /home/uli/opencv/opencv-3.0.0/modules/videoio/src/cap_ffmpeg.cpp:45:0:
    /home/uli/opencv/opencv-3.0.0/modules/videoio/src/cap_ffmpeg_impl.hpp:1546:71: error: use of enum ‘AVCodecID’ without previous declaration
    /home/uli/opencv/opencv-3.0.0/modules/videoio/src/cap_ffmpeg_impl.hpp:1556:83: error: use of enum ‘AVCodecID’ without previous declaration
    make[2]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_ffmpeg.cpp.o] Error 1

I took a quick look at the code, and the reason for the build error seems a bug in cap_ffmpeg_impl.hpp.  Early in the file, `CV_CODEC_ID` gets defined to be `AVCodecID` or `CodecID` depending on FFmpeg version:

    #if LIBAVCODEC_BUILD >= CALC_FFMPEG_VERSION(54,25,0)
    #  define CV_CODEC_ID AVCodecID 
    #  define CV_CODEC(name) AV_##name
    #else
    #  define CV_CODEC_ID CodecID
    #  define CV_CODEC(name) name
    #endif

But on lines 1546 and 1556 (errors above), `AVCodecID` is used instead of `CV_CODEC_ID`.  Fixing this made my build work.  I posted this solution on [stackoverflow](http://stackoverflow.com/a/31818445/1628638), where someone else ran into the issue.  The same issue is also reported at least twice on http://answers.opencv.org.

**Comment by StevenPuttemans** [comment]
Could you provide a pull request with the fix?

**Comment by ulrichstern** [comment]
I have so far refused to learn git.  May have some time tonight and can use your comment as motivation.  :)

**Comment by StevenPuttemans** [comment]
@ulrichstern actually I just checked, it is already fixed! No need to supply it again.
rule 1546: https://github.com/Itseez/opencv/blob/master/modules/videoio/src/cap_ffmpeg_impl.hpp#L1546
rule 1556: https://github.com/Itseez/opencv/blob/master/modules/videoio/src/cap_ffmpeg_impl.hpp#L1556

This can be closed down.

**Comment by alalek** [comment]
Use latest master branch

**Comment by ulrichstern** [comment]
Sorry for that; I had done some searches for this bug in the issue tracker, but should have also checked the master branch...  But learned how to do pull requests in the process.  :)

**Comment by StevenPuttemans** [comment]
:+1: no problem!

**Comment by bronzelion** [comment]
Thanks @ulrichstern ! That fix helped me move on!

**Comment by anderwm** [comment]
Pretty sure I just had this same issue, did it sneak back in the code?

**Comment by Cxuef** [comment]
I checkout the master branch , and it also compile fail with link ../../lib/libopencv_videoio.so.

**Comment by VolgGTU** [comment]
Hi.
I have installed opencv like your video. But function CaptureVideo in opencv can not open *.avi file. Then i have installed ffmpeg for Video I/O, and have this bug. Please help me!
[root@node24 release]# make
[  3%] Built target libtiff
[  7%] Built target libjpeg
[ 10%] Built target libjasper
[ 16%] Built target IlmImf
[ 16%] Built target opencv_core_pch_dephelp
[ 16%] Built target pch_Generate_opencv_core
[ 18%] Built target opencv_core
[ 18%] Built target opencv_ts_pch_dephelp
[ 18%] Built target pch_Generate_opencv_ts
[ 19%] Built target opencv_flann_pch_dephelp
[ 19%] Built target pch_Generate_opencv_flann
[ 19%] Built target opencv_flann
[ 20%] Built target opencv_imgproc_pch_dephelp
[ 20%] Built target pch_Generate_opencv_imgproc
[ 23%] Built target opencv_imgproc
[ 23%] Built target opencv_highgui_pch_dephelp
[ 24%] Built target pch_Generate_opencv_highgui
[ 24%] Linking CXX shared library ../../lib/libopencv_highgui.so
/usr/bin/ld: /usr/local/lib/libavcodec.a(avpacket.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libavcodec.a: could not read symbols: Bad value
collect2: ld returned 1 exit status
make[2]: * [lib/libopencv_highgui.so.2.4.9] Error 1
make[1]: * [modules/highgui/CMakeFiles/opencv_highgui.dir/all] Error 2
make: * [all] Error 2
[root@node24 release]# java --version
Unrecognized option: --version
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
[root@node24 release]# java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)﻿
