### ISSUE TITLE
Error while compiling about IPP

### ISSUE THREAD

**Issue by EnigmaHuang** [Itseez/opencv#5890]
I tried to compile OpenCV 3.1 on a Cent OS 7. All the required packages were installed. When compiling, errors like below happened:

Linking CXX executable ../../bin/opencv_annotation
../../lib/libopencv_core.so.3.1.0: undefined reference to `ippiTranspose_16u_C4IR'
../../lib/libopencv_core.so.3.1.0: undefined reference to `ippiMean_StdDev_16u_C1R'
../../lib/libopencv_imgproc.so.3.1.0: undefined reference to `ippiFilterSobelHorizBorder_8u16s_C1R'

CMake downloaded the IPP package and did not change any of it. How should I fix it?

**Comment by alalek** [comment]
CMake and `make VERBOSE=1` outputs are required.

**Comment by EnigmaHuang** [comment]
Linking CXX executable ../../bin/opencv_annotation
cd /home/enigma/waifu2x/opencv-3.1.0/build/apps/annotation && /usr/bin/cmake -E cmake_link_script CMakeFiles/opencv_annotation.dir/link.txt --verbose=1
/usr/bin/c++      -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -ffunction-sections -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG       CMakeFiles/opencv_annotation.dir/opencv_annotation.cpp.o  -o ../../bin/opencv_annotation -rdynamic -ldl -lm -lpthread -lrt ../../../3rdparty/ippicv/unpack/ippicv_lnx/lib/intel64/libippicv.a ../../lib/libopencv_core.so.3.1.0 ../../lib/libopencv_highgui.so.3.1.0 ../../lib/libopencv_imgproc.so.3.1.0 ../../lib/libopencv_imgcodecs.so.3.1.0 ../../lib/libopencv_videoio.so.3.1.0 ../../lib/libopencv_imgcodecs.so.3.1.0 ../../lib/libopencv_imgproc.so.3.1.0 ../../lib/libopencv_core.so.3.1.0 -Wl,-rpath,/home/enigma/waifu2x/opencv-3.1.0/build/lib: 
../../lib/libopencv_core.so.3.1.0: undefined reference to `ippiTranspose_16u_C4IR'
../../lib/libopencv_core.so.3.1.0: undefined reference to `ippiMean_StdDev_16u_C1R'

**Comment by alalek** [comment]
All is fine in the linker command: `../../../3rdparty/ippicv/unpack/ippicv_lnx/lib/intel64/libippicv.a`
What is about CMake output (run `cmake .`)?
Do you build from scratch (clean build directory)?

BTW, IPP symbol names should have "ippicv" prefix: `ippicviTranspose_16u_C4IR`:
```
3rdparty/ippicv/unpack/ippicv_lnx/include/ippicv_redefs.h:#define ippiTranspose_16u_C4IR ippicviTranspose_16u_C4IR
```
Try to rebuild.

**Comment by EnigmaHuang** [comment]
Thank you for reminding me to "build from scratch" and the IPP symbol names. I have an ICC 15 in the CentOS and I sourced its environment vars in .bashrc, so when compiling the system uses the IPP in ICC instead of in 3rdparty/ippicv. 
It's really my mistake.

**Comment by ziyuang** [comment]
Does OpenCV 3.1.0 actually work with Intel IPP 9.0(.1)?

**Comment by EnigmaHuang** [comment]
I did not try IPP 9.0(.1), maybe it has some problems with the compiler

**Comment by alalek** [comment]
> Does OpenCV 3.1.0 actually work with Intel IPP 9.0(.1)?

Build is successful with latest IPP 9.0.1 (`cmake -DIPPROOT=...`)

**Comment by acgtyrant** [comment]
@EnigmaHuang 发现野生的小黄！

**Comment by EnigmaHuang** [comment]
@acgtyrant 哼，难道还有被圈养的……
