### ISSUE TITLE
tests modules build fails (Clang) conflicting types for sigsetjmp

### ISSUE THREAD

**Issue by PolarNick239** [Itseez/opencv#5740]
When trying to compile with Clang-3.7:
```
In file included from /home/polarnick/libraries/opencv/master/opencv/modules/ts/src/ts.cpp:116:
/usr/include/setjmp.h:59:12: error: conflicting types for '__sigsetjmp'
extern int __sigsetjmp (struct __jmp_buf_tag __env[1], int __savemask) __THROWNL;
           ^
/usr/include/pthread.h:745:12: note: previous declaration is here
extern int __sigsetjmp (struct __jmp_buf_tag *__env, int __savemask) __THROWNL;
           ^
1 error generated.
modules/ts/CMakeFiles/opencv_ts.dir/build.make:146: recipe for target 'modules/ts/CMakeFiles/opencv_ts.dir/src/ts.cpp.o' failed
```

### Relevant issues:
 - https://code.google.com/p/chromium/issues/detail?id=474638
 - http://stackoverflow.com/questions/31366995/cannot-compile-opencv
 - http://stackoverflow.com/questions/19642590/libtooling-cant-find-stddef-h-nor-other-headers/19673558#19673558

### Workaround:
Don't build tests module: run cmake with `-DBUILD_opencv_ts=0`.

**Comment by andreygursky** [comment]
This has been fixed in 2.4 a year ago: https://github.com/Itseez/opencv/commit/6bb6039ebb6cb21f33515212af5bbd2c468d472f. Unfortunately, without any meaningful commit message (i.e., why this was needed for QNX support). The recent commit message doesn't explain it either. It doesn't even refer to this bug report.
