### ISSUE TITLE
Opencv build for python crashes on link to hdf5.h on ubuntu 15.10

### ISSUE THREAD

**Issue by dickkniep** [Itseez/opencv#6050]
[ 87%] Building CXX object modules/optflow/CMakeFiles/opencv_test_optflow.dir/test/ocl/test_motempl.cpp.o
Linking CXX executable ../../bin/opencv_test_optflow
[ 87%] Built target opencv_test_optflow
[ 87%] Built target opencv_perf_stitching_pch_dephelp
[ 87%] Built target pch_Generate_opencv_perf_stitching
[ 88%] Built target opencv_stitching_pch_dephelp
[ 88%] Built target pch_Generate_opencv_stitching
[ 89%] Built target opencv_stitching
[ 89%] Built target opencv_perf_stitching
[ 89%] Built target opencv_test_stitching_pch_dephelp
[ 89%] Built target pch_Generate_opencv_test_stitching
[ 89%] Built target opencv_test_stitching
[ 89%] Building CXX object modules/python2/CMakeFiles/opencv_python2.dir/__/src2/cv2.cpp.o
In file included from /tmp/opencv/opencv/build/modules/python2/pyopencv_generated_include.h:11:0,
                 from /tmp/opencv/opencv/modules/python/src2/cv2.cpp:12:
/tmp/opencv/opencv_contrib/modules/hdf/include/opencv2/hdf/hdf5.hpp:40:18: fatal error: hdf5.h: No such file or directory
compilation terminated.

The following packages are installed:
dick@dick-thuis:~/PycharmProjects/cctools/scripts_linux$ dpkg -l | grep hdf5
ii  hdf5-helpers                                  1.8.15-patch1+docs-4                       amd64        Hierarchical Data Format 5 (HDF5) - Helper tools
ii  libhdf5-10:amd64                              1.8.15-patch1+docs-4                       amd64        Hierarchical Data Format 5 (HDF5) - runtime files - serial version
ii  libhdf5-cpp-10:amd64                          1.8.15-patch1+docs-4                       amd64        Hierarchical Data Format 5 (HDF5) - C++ libraries
ii  libhdf5-dev                                   1.8.15-patch1+docs-4                       amd64        Hierarchical Data Format 5 (HDF5) - development files - serial version
d

**Comment by alalek** [comment]
Same problem here: #6016

**Comment by Shreyash23** [comment]
Any fix? I'm on Ubuntu 16.04

**Comment by krit4rth** [comment]
[This is solved here](https://github.com/Itseez/opencv/issues/6016)

**Comment by Joshi-Harsh** [comment]
I faced the same issue. I am on Ubuntu 16.04.1 x64

**Comment by kleinash** [comment]
Any solution to this?

**Comment by jansila** [comment]
Still works well on `Ubuntu 16.04 LTS` as of today.
