### ISSUE TITLE
compile problem on FreeBSD 10.2, PTHREAD_RECURSIVE_MUTEX_INITIALIZER

### ISSUE THREAD

**Issue by pipehappy** [Itseez/opencv#5423]
Try to compile on FreeBSD 10.2, but get the follow error:

    opencv/modules/core/src/parallel_pthreads.cpp:257:57 error: use of undeclared identifier
    'PTHREAD_RECURSIVE_MUTEX_INITIALIZER'
    ...

A short search shows there is no portable way to statically initialize a recursive mutex. Anyone use opencv on freebsd would shine some light upon this? Thank you!

**Comment by StevenPuttemans** [comment]
Just build OpenCV without pthreads support by disabling the option in cmake?

**Comment by pipehappy** [comment]
It looks like PTHREAD_RECURSIVE_MUTEX_INITIALIZER is a GNU/Linux extension. 

http://stackoverflow.com/questions/7037481/c-how-do-you-declare-a-recursive-mutex-with-posix-threads

shows a way to initialize it dynamically but statically initialization is required here. Maybe we just need a static block here.

**Comment by luaraneda** [comment]
Please see the issue that I just created, [#5476](https://github.com/Itseez/opencv/issues/5476), and comment if needed.
I think it has more information and is more general because affects all platforms.

**Comment by alalek** [comment]
@pipehappy Does https://github.com/Itseez/opencv/pull/5765 patch work for you?

**Comment by qiukaijia** [comment]
I has the same problem in Alpine linux. Has anyone solved this problem?

**Comment by StevenPuttemans** [comment]
@qiukaijia did you try the mentioned fix by @alalek?

**Comment by qiukaijia** [comment]
@StevenPuttemans I have just modified file with this commit: https://github.com/opencv/opencv/commit/78376c0f63834642b8133ab5d3b5f658d65a0bb2#diff-44c4b36c20fff2956b4c317dd0502eea
however, there are compile errors:
say  CV_SINGLETON_LAZY_INIT_REF is not declared in this scope
