### ISSUE TITLE
Lucas-Kanade Tutorial not working on Python using Mac.

### ISSUE THREAD

**Issue by opencv-pushbot** [Itseez/opencv#4863]
Transferred from http://code.opencv.org/issues/4008
```
|| Quang Nguyen on 2014-11-14 10:12
|| Priority: Normal
|| Affected: branch 'master' (3.0-dev)
|| Category: samples
|| Tracker: Bug
|| Difficulty: 
|| PR: 
|| Platform: x64 / Mac OSX
```

Lucas-Kanade Tutorial not working on Python using Mac.
-----------
```
http://docs.opencv.org/trunk/doc/py_tutorials/py_video/py_lucas_kanade/py_lucas_kanade.html#lucas-kanade

It breaks down when calling cv2.calcOpticalFlowPyrLK(). lktracker.py in the samples also does not work and outputs the same error.


Output:
OpenCV Error: Image step is wrong (Step must be a multiple of esz1) in setSize, file /tmp/opencv-P6BF4O/modules/core/src/matrix.cpp, line 297
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /tmp/opencv-P6BF4O/modules/core/src/matrix.cpp:297: error: (-13) Step must be a multiple of esz1 in function setSize

Abort trap: 6
```

History
-------
##### Quang Nguyen on 2014-11-16 06:36
```
I just installed openCV through anaconda instead of brew and this fixes the error.

First I installed the anaconda package:
http://continuum.io/downloads#all

Then I installed the openCV package via terminal: "conda install opencv"
After that reupdating numpy with: "conda update numpy"

It works now I also see that anaconda is using openCV 2.4.8.
OpenCV 2.4.9 through brew did not work with the samples either, it produced another kind of error in matrix.cpp.
So everything still works in openCV 2.4.8 on Python in Mac but it breaks down in the versions after that.
```
