### PR TITLE
Fix build with GCC 4.6

### PR DESCRIPTION
**Pull request by alalek**
Ubuntu 12.04
GCC 4.6

```
In file included from /home/build/opencv/modules/photo/src/fast_nlmeans_denoising_invoker.hpp:48:0,
                 from /home/build/opencv/modules/photo/src/denoising.cpp:44:
/home/build/opencv/modules/photo/src/fast_nlmeans_denoising_invoker_commons.hpp:71:19: error: ‘sampleType’ does not name a type
/home/build/opencv/modules/photo/src/fast_nlmeans_denoising_invoker_commons.hpp:71:19: note: (perhaps ‘typename pixelInfo_<T>::sampleType’ was intended)
/home/build/opencv/modules/photo/src/fast_nlmeans_denoising_invoker_commons.hpp:76:19: error: ‘sampleType’ does not name a type
/home/build/opencv/modules/photo/src/fast_nlmeans_denoising_invoker_commons.hpp:76:19: note: (perhaps ‘typename pixelInfo_<T>::sampleType’ was intended)

/home/build/opencv/modules/photo/src/fast_nlmeans_multi_denoising_invoker.hpp:247:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/home/build/opencv/modules/photo/src/fast_nlmeans_multi_denoising_invoker.hpp:249:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
```

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
:+1:
