### ISSUE TITLE
Building Opencv with ffmpeg built from source gives linking errors

### ISSUE THREAD

**Issue by Corentin-Hamel** [Itseez/opencv#5930]
Hi,
I'm trying build opencv to used it on ASW Lambda. Opencv is going to be uploaded as a zip file so I'm doing a static build with BUILD_SHARED_LIBS=OFF. I set up WITH_FFMPEG=YES as i will process some video files. 
I didn't want to install ffmpeg with apt-get as I want to have control on where my libraries are installed. I've downloaded ffmpeg and installed it from source to get the libavcodec, libavformat, libavutil and libswscale.
I installed it as follow:
```
./configure --prefix=ffmpeg_build --disable-yasm --enable-shared --cc="gcc -fPIC"
```
I also did: 
```
export LD_LIBRARY_PATH=/path/ffmpeg/ffmpeg_build/lib
export PKG_CONFIG_PATH=/path/ffmpeg/ffmpeg_build/lib/pkgconfig
```
I can see ffmpeg was well installed by running ./ffmpeg:
```
ffmpeg version N-77722-g3ec5d8f Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.6 (Ubuntu/Linaro 4.6.3-1ubuntu5)
  configuration: --prefix=ffmpeg_build --disable-yasm --enable-shared --cc='gcc -fPIC'
  libavutil      55. 12.100 / 55. 12.100
  libavcodec     57. 22.100 / 57. 22.100
  libavformat    57. 21.101 / 57. 21.101
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6. 23.100 /  6. 23.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
```

Now I'm trying to build opencv and link ffmpeg but it looks like it can't find it. Using the cmake UI i can even specify the path of the libraries as follow.
```
FFMPEG_CODEC_LIB              /home/ubuntu/test_lambda/ffmpeg/ffmpeg_build/lib/libavcodec.so.57                               
 FFMPEG_FORCE_TCP            ON                                                                                           
 FFMPEG_FORMAT_LIB           /home/ubuntu/test_lambda/ffmpeg/ffmpeg_build/lib/libavformat.so.57                              
 FFMPEG_INCLUDE_DIR         /home/ubuntu/test_lambda/ffmpeg/ffmpeg_build/include                                         
 FFMPEG_LIB_DIR                   /home/ubuntu/test_lambda/ffmpeg/ffmpeg_build/include/../lib                                  
 FFMPEG_SWSCALE_LIB        /home/ubuntu/test_lambda/ffmpeg/ffmpeg_build/lib/libswscale.so.4                               
 FFMPEG_UTIL_LIB                  /home/ubuntu/test_lambda/ffmpeg/ffmpeg_build/lib/libavutil.so.55          
```
But running the cmake command give the following:
```
Video I/O:
--     DC1394 1.x:     NO
--     DC1394 2.x:     NO
--     FFMPEG:         YES
--       codec:             NO
--       format:            NO
--       util:                  NO
--       swscale:          NO
```
Then if i still try to use make i get:
```
Linking CXX shared library ../../lib/libopencv_photo.so
In file included from /home/ubuntu/test_lambda/rb-opencv/modules/highgui/src/cap_ffmpeg.cpp:45:0:
/home/ubuntu/test_lambda/rb-opencv/modules/highgui/src/cap_ffmpeg_impl.hpp:71:6: error: #error "libswscale is necessary to build the newer OpenCV ffmpeg wrapper"
```
OpenCV can't find my libavcodec etc... and I have no clue how to fix that. I don't understand why it can't find with all the steps I have done before.
Any ideas? 
Thanks for your help.

**Comment by alalek** [comment]
Do you have installed `pkg-config` binary?
If no, then try to install `pkg-config` package and rerun cmake (clean build directory) to find ffmpeg via standard way (with `PKG_CONFIG_PATH`).

**Comment by Corentin-Hamel** [comment]
Thanks for your answer. I have pig-config install
```
user$ pkg-config
Must specify package names on the command line
```

**Comment by alalek** [comment]
Your current commit is from "master" ffmpeg branch. It is possible that something is changed in packaging rules.
Are you able to build with ffmpeg sources from 2.7/2.8 branch?

**Comment by Corentin-Hamel** [comment]
Sorry I forgot to mention I'm using opencv 2.4.11. Did i create the issue at wrong place?

**Comment by alalek** [comment]
It is right place for OpenCV bugs. I mean ffmpeg's branches above.
By the way, could you try to build "master" OpenCV?

**Comment by Corentin-Hamel** [comment]
But OpenCV master is in version 3.x right? I'm still using 2.4 as I din't have a look at all the new changes which may affect my code.
I can try to build ffmpeg 2,8

**Comment by alalek** [comment]
It is to investigate problem only.

**Comment by alalek** [comment]
Could you add output of this command (with fixed valid path)?
```
PKG_CONFIG_PATH=/path/ffmpeg/ffmpeg_build/lib/pkgconfig pkg-config --libs --cflags libavformat
```

**Comment by Corentin-Hamel** [comment]
So i tried different things:
opencv 2.4.11 with ffmpeg 2.8 => same problem
opencv master branch with ffmpeg 2.8 => almost worked !

I'm just getting this error now
```
/home/ubuntu/test_lambda/opencv-3.0/modules/python/src2/cv2.cpp:6:20: fatal error: Python.h: No such file or directory
```
But i'm pretty sure something is wrong with my python paths

your command:
```
PKG_CONFIG_PATH=/path/ffmpeg/ffmpeg_build/lib/pkgconfig pkg-config --libs --cflags libavformat
-Iffmpeg_build/include  -Lffmpeg_build/lib -lavformat 
```

**Comment by alalek** [comment]
pkg-config should return full path (relative paths will not work):
```
$ PKG_CONFIG_PATH=`pwd` pkg-config --libs --cflags libavcodec 
-I/home/alalek/projects/opencv_3rdparty_binary/build/ffmpeg_build/ffmpeg/install/include -L/home/alalek/projects/opencv_3rdparty_binary/build/ffmpeg_build/ffmpeg/install/lib -lavcodec
```
Try to use full path for `configure` `prefix` parameter.

**Comment by Corentin-Hamel** [comment]
So I configured again ffmpeg and now I'm getting this:
```
$ PKG_CONFIG_PATH=/home/ubuntu/test_lambda/ffmpeg/ffmpeg_build/lib/pkgconfig/  pkg-config --libs --cflags libavcodec 
-I/home/ubuntu/test_lambda/ffmpeg/ffmpeg_build/include L/home/ubuntu/test_lambda/ffmpeg/ffmpeg_build/lib -lavcodec  
```
But with opencv 2.4 i still get the same error and can't detect the ffmpeg libraries

**Comment by alalek** [comment]
1) Could you run this commands in 2.4 build directory:
```
cat CMakeCache.txt | grep ffmpeg_build
cat CMakeCache.txt | grep libav
```

2) Run `make VERBOSE=1` to see full command lines and check the passed include paths.

**Comment by Corentin-Hamel** [comment]
1/ Here are the results:
```
$ cat CMakeCache.txt | grep ffmpeg_build
FFMPEG_CODEC_LIB:FILEPATH=/home/ubuntu/test_lambda/ffmpeg/ffmpeg_build/lib/libavcodec.so.56
FFMPEG_FORMAT_LIB:FILEPATH=/home/ubuntu/test_lambda/ffmpeg/ffmpeg_build/lib/libavformat.so.56
FFMPEG_INCLUDE_DIR:PATH=/home/ubuntu/test_lambda/ffmpeg/ffmpeg_build/include
FFMPEG_LIB_DIR:PATH=/home/ubuntu/test_lambda/ffmpeg/ffmpeg_build/include/../lib
FFMPEG_SWSCALE_LIB:FILEPATH=/home/ubuntu/test_lambda/ffmpeg/ffmpeg_build/lib/libswscale.so.3
FFMPEG_UTIL_LIB:FILEPATH=/home/ubuntu/test_lambda/ffmpeg/ffmpeg_build/lib/libavutil.so.54
opencv_highgui_LIB_DEPENDS:STATIC=general;opencv_core;general;opencv_imgproc;general;stdc++;general;dl;general;m;general;pthread;general;rt;general;tbb;general;/usr/lib/libz.so;general;libjpeg;general;libpng;general;/home/ubuntu/test_lambda/ffmpeg/ffmpeg_build/lib/libavcodec.so.56;general;/home/ubuntu/test_lambda/ffmpeg/ffmpeg_build/lib/libavformat.so.56;general;/home/ubuntu/test_lambda/ffmpeg/ffmpeg_build/lib/libavutil.so.54;general;/home/ubuntu/test_lambda/ffmpeg/ffmpeg_build/lib/libswscale.so.3;
```

**Comment by alalek** [comment]
For some reason pkg-config provided empty results on previous steps: `ALIASOF_libav*:INTERNAL` vars are empty (and cached by CMake). Clean build directory and rerun CMake with the right PKG_CONFIG_PATH. This will run pkg-config check again.

P.S. To provide accurate results don't use CMake GUI.

**Comment by Corentin-Hamel** [comment]
1/ So I run this command:
```
$ cmake -D FFMPEG_FORCE_TCP=YES -D FFMPEG_INCLUDE_DIR=/home/ubuntu/test_lambda/ffmpeg/ffmpeg_build/include -D PYTHON_EXECUTABLE=/home/ubuntu/test_lambda/env/bin/python -D PYTHON_INCLUDE_DIR=/home/ubuntu/test_lambda/env/include/python2.7 -D PYTHON_LIBRARY=/usr/lib/libpython2.7.so -D PYTHON_NUMPY_INCLUDE_DIR=/home/ubuntu/test_lambda/env/local/lib/python2.7/site-packages/numpy/core/include -D PYTHON_PACKAGES_PATH=/home/ubuntu/test_lambda/env/local/lib/python2.7/site-packages -D WITH_FFMPEG=YES -D WITH_GSTREAMER=NO -D WITH_PNG=YES -D WITH_TBB=YES -D WITH_V4L=YES -D WITH_CUDA=NO -D WITH_OPENEXR=NO -D WITH_OPENCL=NO
```

and
``` 
$ $ PKG_CONFIG_PATH=/home/ubuntu/test_lambda/ffmpeg/ffmpeg_build/lib/pkgconfig/  pkg-config --libs --cflags libavcodec 
-I/home/ubuntu/test_lambda/ffmpeg/ffmpeg_build/include L/home/ubuntu/test_lambda/ffmpeg/ffmpeg_build/lib -lavcodec  
```

but i still get the same issue and can't find the libs

2/ with opencv 3 and make verbose=1 i get:
```
Scanning dependencies of target opencv_python2
make[2]: Leaving directory `/home/ubuntu/test_lambda/opencv-3.0/build'
make -f modules/python2/CMakeFiles/opencv_python2.dir/build.make modules/python2/CMakeFiles/opencv_python2.dir/build
make[2]: Entering directory `/home/ubuntu/test_lambda/opencv-3.0/build'
/usr/bin/cmake -E cmake_progress_report /home/ubuntu/test_lambda/opencv-3.0/build/CMakeFiles 
[100%] Building CXX object modules/python2/CMakeFiles/opencv_python2.dir/__/src2/cv2.cpp.o
cd /home/ubuntu/test_lambda/opencv-3.0/build/modules/python2 && /usr/bin/c++   -Dopencv_python2_EXPORTS -DTBB_USE_GCC_BUILTINS=1 -D__TBB_GCC_BUILTIN_ATOMICS_PRESENT=1 -D__OPENCV_BUILD=1 -fPIC   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -ffunction-sections -fvisibility=hidden -fvisibility-inlines-hidden -Wno-unused-function -O3 -DNDEBUG  -DNDEBUG -fPIC -I/home/ubuntu/test_lambda/opencv-3.0/build -isystem /home/ubuntu/test_lambda/opencv-3.0/build/3rdparty/tbb/tbb43_20141204oss/include -I/home/ubuntu/test_lambda/opencv-3.0/modules/python/python2/include -I/home/ubuntu/test_lambda/opencv-3.0/modules/python/python2/src -I/home/ubuntu/test_lambda/opencv-3.0/build/modules/python2 -I/home/ubuntu/test_lambda/opencv-3.0/modules/core/include -I/home/ubuntu/test_lambda/opencv-3.0/modules/flann/include -I/home/ubuntu/test_lambda/opencv-3.0/modules/imgproc/include -I/home/ubuntu/test_lambda/opencv-3.0/modules/ml/include -I/home/ubuntu/test_lambda/opencv-3.0/modules/photo/include -I/home/ubuntu/test_lambda/opencv-3.0/modules/video/include -I/home/ubuntu/test_lambda/opencv-3.0/modules/imgcodecs/include -I/home/ubuntu/test_lambda/opencv-3.0/modules/shape/include -I/home/ubuntu/test_lambda/opencv-3.0/modules/videoio/include -I/home/ubuntu/test_lambda/opencv-3.0/modules/highgui/include -I/home/ubuntu/test_lambda/opencv-3.0/modules/objdetect/include -I/home/ubuntu/test_lambda/opencv-3.0/modules/superres/include -I/home/ubuntu/test_lambda/opencv-3.0/modules/features2d/include -I/home/ubuntu/test_lambda/opencv-3.0/modules/calib3d/include -I/home/ubuntu/test_lambda/opencv-3.0/modules/stitching/include -I/home/ubuntu/test_lambda/opencv-3.0/modules/videostab/include -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/home/ubuntu/test_lambda/opencv-3.0/modules/python/src2    -o CMakeFiles/opencv_python2.dir/__/src2/cv2.cpp.o -c /home/ubuntu/test_lambda/opencv-3.0/modules/python/src2/cv2.cpp
/home/ubuntu/test_lambda/opencv-3.0/modules/python/src2/cv2.cpp:6:20: fatal error: Python.h: No such file or directory
compilation terminated.
make[2]: *** [modules/python2/CMakeFiles/opencv_python2.dir/__/src2/cv2.cpp.o] Error 1
make[2]: Leaving directory `/home/ubuntu/test_lambda/opencv-3.0/build'
make[1]: *** [modules/python2/CMakeFiles/opencv_python2.dir/all] Error 2
```

**Comment by Corentin-Hamel** [comment]
I fixed the problem with OpenCV 3. you were right about not using the cake UI! Some flags were wrong.
PYTHON2_INCLUDE_DIR should be PYTHON2_INCLUDE_PATH and PYTHON2_LIBRARY should be -PYTHON2_LIBRARIES.
 I've built opencv 3 without ffmpeg see if i can use the new motion jpeg codec but it can't open a video capture.

**Comment by alalek** [comment]
MJPEG codec works via VideoWriter interface.
You should enable some of these capture backends to work with VideoCapture:
- ffmpeg
- gstreamer
- v4l (video for linux) / v4l2
- etc, like Windows (vfw / dshow) / MacOS / iOS or hardware specific (like OpenNI).

**Comment by Corentin-Hamel** [comment]
1/ ok i thought MJPEG codec was also used to decode video files. As i was saying in this thread I was trying to build opencv with ffmpeg but can't seem to succeed even with openCV3. My problem is i need to upload all my libraries in a zip file (the cv2.so, shared libraries etc). That's why i installed ffmpeg from source to have control on where the libav* where installed and bundle them in my zip file.

2/ Also while building openCV3 i was using the following flags
```
 PYTHON2_INCLUDE_DIR and PYTHON2_LIBRARY
```
but this leads to the error 
```
modules/python/src2/cv2.cpp:6:20: fatal error: Python.h: No such file or directory
```

while using the following flags works
```
PYTHON2_INCLUDE_PATH and PYTHON2_LIBRARIES
```
Even if cmake is print the following
```
Could NOT find PythonLibs (missing:  PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
```
and
```
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    PYTHON2_INCLUDE_PATH
    PYTHON2_LIBRARIES
```
It looks cmake is telling you it needs PYTHON2_INCLUDE_DIR and PYTHON2_LIBRARY but it actually needs PYTHON2_INCLUDE_PATH and PYTHON2_LIBRARIES to compile the python bindings.
Is that a bug?

**Comment by Corentin-Hamel** [comment]
Is v4l abling you to read  video file with VideoCapture ? compiling opencv with WITH_V4L=YESY AND WITH_LIBV4L=YES WITH_FFMPEG=NO, I can't read video file isOpened() is returning false.
I would like to avoid ffmpeg as shared libraries decencies if it's possible.

Thanks a lot for you help by the way

**Comment by alalek** [comment]
v4l reads data from camera device (in general).

**Comment by colonel-tan** [comment]
Thanks for opening up this issue. I have the same problem and due to academic stuffs, I need to stay with 2.4.11. So how do I build it on this version without moving on to OpenCV 3? (My project won't involve video at all)

Thanks.

**Comment by alalek** [comment]
FFMPEG 3.0 patches are backported to 2.4 branch (will be released with 2.4.13)

@colonel-tan 
Just disable video support via CMake option: `cmake -DWITH_FFMPEG=OFF ...`

**Comment by colonel-tan** [comment]
Got it to work, thanks alalek.

**Comment by ClementViel** [comment]
Just to add a solution because i ran throught the same problem of libswscale not being detected whereas it was installed on its latest version.

Problem is that cmake use `pkg-config` to check for modules presents and pkg-config does not know of all the package present in your system but only those which were compiled with pkg-config flags 

cc `pkg-config --cflags --libs x` -o myapp myapp.c (sorry for bad markdown but there are actually backquotes that surround pkg-config --cflags --libs x

from [freedesktop](https://people.freedesktop.org/~dbn/pkg-config-guide.html) page

when typing `pkg-config --list-all`no libswscale was showing up. But you can easily add packages or libraries already present in your system to pkg-config. You just have to create a file called <package_name>.pc in /usr/share/pkgconfig/ directory and fill it with correct fields. 

So to add libswscale to pkg-config list, just do the following 

- create /usr/share/pkgconfig/libswscale.pc
- edit file. Should look like 
`Name: libswscale
 Description: libswscale
 Version: 300
 libswscaledir=/usr/lib/x86_64-lniux-gnu/libswscale.so`

- cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local ..  

it should now compile with ffmpeg support.

**Comment by harshal2802** [comment]
Any body solved this issue?
I am also facing error where VideoCapture is not working..
I need to create a lambda function using opencv(3.1.0) numpy for video processing.
Kindly help me with specific steps as I already tried many methods to work it around...

Any help will be really helpful for me to move forward..

**Comment by abratchik** [comment]
Yes, please update OpenCV from upstream and rebuild - it should be working fine

**Comment by harshal2802** [comment]
I am getting this issue when using (
https://www.archlinux.org/packages/extra/x86_64/opencv/) upstream version.
Is this the correct version or is there any other version of it.
Kindly let me know the relevant source for building opencv for lambda
function

Thanks
Harshal
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libavcodec.so.57: cannot open shared object file: No such file
or directory

**Comment by alalek** [comment]
> libavcodec.so.57: cannot open shared object file

Try to update `LD_LIBRARY_PATH` environment variable and add path of mentioned library.

**Comment by harshal2802** [comment]
ImportError: /usr/lib/libgdal.so.1: undefined symbol:
sqlite3_column_table_name

I used LD_LIBRARY_PATH now above error is coming..

**Comment by alalek** [comment]
Remove your OpenCV package (it is broken anyway) and try to follow these tutorials: http://docs.opencv.org/master/df/d65/tutorial_table_of_content_introduction.html
