### ISSUE TITLE
Building iOS framework with build_framework.py fails

### ISSUE THREAD

**Issue by SSteve** [Itseez/opencv#6093]
Attempting to build iOS framework with build_framework.py gives the following error:

```
The following build commands failed:
	CompileC /Users/steve/Development/GitHub/ios/build/arm64-iPhoneOS/3rdparty/zlib/OpenCV.build/Release-iphoneos/zlib.build/Objects-normal/arm64/gzread.o 3rdparty/zlib/gzread.c normal arm64 c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
============================================================
ERROR: Command '['xcodebuild', 'IPHONEOS_DEPLOYMENT_TARGET=6.0', 'ARCHS=arm64', '-sdk', 'iphoneos', '-configuration', 'Release', '-parallelizeTargets', '-jobs', '4', '-target', 'ALL_BUILD', 'build']' returned non-zero exit status 65
============================================================
Traceback (most recent call last):
  File "opencv/platforms/ios/build_framework.py", line 87, in build
    self._build(outdir)
  File "opencv/platforms/ios/build_framework.py", line 81, in _build
    self.buildOne(t[0], t[1], mainBD, cmake_flags)
  File "opencv/platforms/ios/build_framework.py", line 139, in buildOne
    execute(buildcmd + ["-target", "ALL_BUILD", "build"], cwd = builddir)
  File "opencv/platforms/ios/build_framework.py", line 34, in execute
    retcode = check_call(cmd, cwd = cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['xcodebuild', 'IPHONEOS_DEPLOYMENT_TARGET=6.0', 'ARCHS=arm64', '-sdk', 'iphoneos', '-configuration', 'Release', '-parallelizeTargets', '-jobs', '4', '-target', 'ALL_BUILD', 'build']' returned non-zero exit status 65
```

Command:
`python opencv/platforms/ios/build_framework.py ios`

OS X 10.11.3
MacBook Pro/2.8 GHz Core 2 Duo
XCode 7.2.1

**Comment by alalek** [comment]
There is no real error reason in this log cut. Please add more info.

BTW, We can't reproduce this problem with XCode 7.2: http://pullrequest.opencv.org/buildbot/builders/master_iOS-mac/builds/194

**Comment by SSteve** [comment]
Perhaps it's hardware-related? Compiles fine on my iMac/4 GHz i7, OS X 10.11.2, XCode 7.1.1. I'll update this machine to OS X 10.11.3/XCode 7.2 and see what happens.

Have you ever tried compiling with a Core 2 Duo? Is the Core 2 Duo supported for this purpose?

**Comment by alb423** [comment]
I have the same problem. 

OS X 10.11.3
MacBook Pro/2.5 GHz Intel Core i5
XCode 7.2.1

**Comment by mshabunin** [comment]
Please, provide full build logs (via attachment, pastebin or gist). Try to make clean build, try to install all updates and restart computer.

**Comment by alb423** [comment]
Hi mshabunin,

The error log is attached.  [implicit_declaration_of_function_is_invalid_in_C99.txt](https://github.com/Itseez/opencv/files/136482/implicit_declaration_of_function_is_invalid_in_C99.txt)

The error shows
> gzwrite.c:90:21: error: 
      implicit declaration of function 'write' is invalid in C99
gzwrite.c:579:9: error: 
      implicit declaration of function 'close' is invalid in C99

If I add `"#include <unistd.h>"` in gzguts.h, this error can be fixed.

**Comment by alalek** [comment]
Actually there is already `include <unistd.h>` [statement](https://github.com/opencv/opencv/blob/a679e4ca7c0b8f05e3620647304f0f7f9ed17608/3rdparty/zlib/zconf.h.cmakein#L454). But it is under condition from configuration stage.

Could someone put CMake output with these lines?
```
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - failed
```
